### ISSUE TITLE
Let's get our .nuspec improved

### ISSUE THREAD

**Issue by spacesynth** [aquacash5/magic-wormhole-exe#1]
Commands used:
```
choco new magic-wormhole
```
DIR tree:
```
magic-wormhole.nuspec
tools\bin\wormhole.exe
tools\LICENSE
tools\README
```
Notepad++ the ```.nuspec```

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>magic-wormhole.portable</id>
    <version>0.12.0</version>
    <title>magic-wormhole</title>
    <authors>aquacash5,vaporwave9,warner</authors>
    <owners>aquacash5</owners>
    <licenseUrl>https://github.com/magic-wormhole/magic-wormhole/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/aquacash5/magic-wormhole-exe</projectUrl>
    <iconUrl>https://avatars.githubusercontent.com/u/59107264</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Get things from one computer to another, safely.

This package provides a library and a command-line tool named wormhole, which makes it possible to get arbitrary-sized files and directories (or short pieces of text) from one computer to another. The two endpoints are identified by using identical "wormhole codes": in general, the sending machine generates and displays the code, which must then be typed into the receiving machine.

The codes are short and human-pronounceable, using a phonetically-distinct wordlist. The receiving side offers tab-completion on the codewords, so usually only a few characters must be typed. Wormhole codes are single-use and do not need to be memorized.</description>
    <summary>Get things from one computer to another, safely.</summary>
    <releaseNotes>[Software Changelog](https://github.com/magic-wormhole/magic-wormhole/blob/master/NEWS.md)
[Package Changelog](https://github.com/aquacash5/magic-wormhole-exe)</releaseNotes>
    <copyright>Remove or add one this is free software anyways</copyright>
    <tags>filetransfer</tags>
    <projectSourceUrl>https://github.com/magic-wormhole/magic-wormhole</projectSourceUrl>
    <packageSourceUrl>https://github.com/aquacash5/magic-wormhole-exe</packageSourceUrl>
    <bugTrackerUrl>https://github.com/aquacash5/magic-wormhole-exe/issues</bugTrackerUrl>
  </metadata>
</package>
```

Inside the dir with your ```.nuspec``` you run:
```choco pack magic-wormhole.nuspec```
And you receive a ```magic-wormhole.0.12.0.nupkg``` which you can install or remove like:

```choco install magic-wormhole -dv -s .```
or
```choco uninstall magic-wormhole -dv -s .```

Tests work:

![grafik](https://user-images.githubusercontent.com/64961250/108622303-21dc2c00-7438-11eb-9411-b2f5f675a662.png)

```choco install magic-wormhole.portable -dv -s .```
Note my package name changed to emphasize it is a ```.portable``` release.

Edit:
updated build artifacts
[magic-wormhole.zip](https://github.com/aquacash5/magic-wormhole-exe/files/6017550/magic-wormhole.zip)
[magic-wormhole.portable.0.12.0.nupkg.zip](https://github.com/aquacash5/magic-wormhole-exe/files/6017552/magic-wormhole.portable.0.12.0.nupkg.zip)

Thoughts fellow coder?

**Comment by aquacash5** [comment]
I will look over this when I get home

**Comment by aquacash5** [comment]
Is it better to package the executable, or have it download from the release url?

**Comment by spacesynth** [comment]
It is absolutely fine to package it. Many other projects on Chocolatey do this. Such as the bitcoin wallet "electrum".

Edit for reference:
https://chocolatey.org/packages/electrum.portable

Edit 2:
I also like the idea that old versions can be rolled back at will of the user, since they remain in a second repo.
There are all previous releases of electrum accessible, should there be the need to use them because of a bug.

**Comment by aquacash5** [comment]
Check out my PR with the chocolatey setup.

Edit:
Particularly look at the `.github/workflows/create-executable.yml`

The second half are scripts that would automate the deployment.

**Comment by spacesynth** [comment]
Oh this is a huge improvement already over what I cooked up. I see now how you retrieve the data to automate the process. Crossing my fingers that it pushes fine to the Community repo and gets reviewed soon when you try. I'll try to see if I can adapt my plans for [age-encryption ](https://github.com/FiloSottile/age) to reach your level of deployment 🤞

Edit:
Full disclosure that I will need to read the docs more to understand it all.

**Comment by aquacash5** [comment]
Ok, It is going through moderation.

https://chocolatey.org/packages/magic-wormhole.portable/0.12.0

**Comment by spacesynth** [comment]
Thanks for the link, I'll thoroughly test tomorrow on a spare machine that has not seen either Chocolatey or magic-wormhole.
Cheers to you for pulling through all night to make it work! I'm just glad this solves many issues at once and reminds me of the motto of the pipenv developers: "Windows is a first-class citizen, in our world."

Today one step closer again with this CLI tool in a sensitive repository. I've always missed apt-get on Windows.

**Comment by aquacash5** [comment]
All automated checks have passed. Just waiting for a manual review.

**Comment by spacesynth** [comment]
I eventually stopped waiting for manual review to happen, since I fear this might be done by hobbyists in their free time and forced the installation by providing version à la:
```choco install magic-wormhole.portable --version=0.12.0```

It's installing just fine and runs well after you fixed the duplication of $args in the morning ;)

**Comment by aquacash5** [comment]
Everything is approved!

https://community.chocolatey.org/packages/magic-wormhole/0.12.0

**Comment by spacesynth** [comment]
Thanks for the update! It's been a busy week and I finally could read all of my inbox.
Glad the reviewer only suggested minor tweaks and was providing information what to do.
